services:
  php:
    image: php:8.2-apache
    container_name: php-backend
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./backend/docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - app-network
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfonyuser
      MYSQL_PASSWORD: symfonypass
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
