services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - db
    volumes: 
      - ./backend:/var/www/html
    environment:
      DATABASE_URL: "mysql://root:root@db:3306/skillsculptor"
    ports:
      - 8080:80

# RUN apt-get update && apt-get install -y \
#     libicu-dev \
#     libzip-dev \
#     && docker-php-ext-install \
#     intl \
#     pdo_mysql \
#     zip

# CMD symfony server:start --allow-all-ip --no-tls --port=80 --dir=/var/www/html && \
#     php bin/console doctrine:schema:create

  db:
    container_name: db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: skillsculptor
    ports:
      - 3306:3306

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80