services:
  
  web:
    container_name: backend
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:8
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
